<?php

/**
 * @file
 * Commerce Shipmondo Checkout module hooks.
 */

use Drupal\commerce_shipping\Form\ShipmentForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_shipmondo_checkout_form_commerce_shipment_default_form_alter(array &$form, FormStateInterface $form_state): void {
  if (empty($form['shipping_method']['widget'][0]['#options'])) {
    return;
  }

  $form['shipping_method']['widget'][0]['#ajax'] = [
    'callback' => [ShipmentForm::class, 'ajaxRefreshForm'],
  ];
}

/**
 * Implements hook_theme().
 */
function commerce_shipmondo_checkout_theme($existing, $type, $theme, $path): array {
  return [
    'shipmondo_service_point' => [
      'variables' => [
        'carrier_code' => NULL,
        'name' => NULL,
        'address' => NULL,
        'zipcode' => NULL,
        'city' => NULL,
      ],
    ],
  ];
}
